version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    networks:
      - benchnet

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy
    container_name: toxiproxy
    ports:
      - "8474:8474"  # Control proxy API
      - "6380:6380"  # Redis proxy
    volumes:
      - ./toxiproxy.json:/config.json
    command: ["toxiproxy-server", "--config", "/config.json"] #proxy traffic + runtime setting in json
    environment:
      - TOXIPROXY_HOST=0.0.0.0
    networks:
      - benchnet

  redis-client:
    image: redis
    depends_on:
      - toxiproxy
    entrypoint: ["redis-cli", "-h", "localhost", "-p", "6380"] 
    tty: true             # Attach terminal
    networks:
      - benchnet

networks:
  benchnet:
    driver: bridge
